{
 "title": "locust_1s",
 "tags": [
  "locust",
  "elasticsearch"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "locust_es_datasource", "label": "locust_es_datasource", "query": "elasticsearch" },
   { "name": "show_source_row", "label": "show_source_row", "query": "2" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "集群资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage Details",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"$namespace\",container_label_io_kubernetes_pod_name=\"$pod\",container_label_io_kubernetes_container_name=~\"$container\"}[1m])) by(container_label_io_kubernetes_container_name)",
       "legendFormat": "usage({{container_label_io_kubernetes_container_name}})",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      },
      {
       "expr": "kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"}",
       "legendFormat": "requests({{container}})"
      },
      {
       "expr": "kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"}"
      }
     ]
    }
   ]
  },
  { "title": "统计数据", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "locust运行概况",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "失败率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "locust运行状态",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "压测客户端数量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "users-rps-rt数值",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "曲线图",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "users-rps-rt曲线",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "users-rps曲线",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "rt曲线",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "原始数据", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "原始数据",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "${show_source_row}" }, "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "原始数据",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "${show_source_row}" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "原始数据",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "2" }, "type": "raw_document" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "全部",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "locust运行概况",
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "1" }, "type": "raw_data" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "压测客户端数量",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 9, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "users-rps-rt曲线",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "原始数据",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "${show_source_row}" }, "type": "logs" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}